FROM python:3.9.16-alpine3.17
LABEL maintainer="Sašo Skube saso.skube@gmail.com"

ARG PASS=korenina
RUN apk add --update --no-cache \
    openssh \
    bash \
    # Ansible requirements
    unzip \
    # For update-alternatives
    dpkg \
  && echo ${PASS} \
  && echo -n "root:${PASS}" | chpasswd

COPY simulator_sshd_config /etc/ssh/sshd_config

RUN /usr/bin/ssh-keygen -A \
  && ssh-keygen -t rsa -b 4096 -f  /etc/ssh/ssh_host_key

CMD ["/usr/sbin/sshd", "-D"]
